"""added photo_url for users

Revision ID: 6dfcbe447662
Revises: dc8a2a1bf790
Create Date: 2024-11-13 22:24:36.647698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dfcbe447662'
down_revision: Union[str, None] = 'dc8a2a1bf790'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo_url', sa.String(length=255), server_default='/images/default.svg', nullable=False))
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'photo_url')
    # ### end Alembic commands ###
