"""added birthdate for users

Revision ID: dc8a2a1bf790
Revises: 5a5de06e543b
Create Date: 2024-11-06 20:20:20.503495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc8a2a1bf790'
down_revision: Union[str, None] = '5a5de06e543b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birthdate', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birthdate')
    # ### end Alembic commands ###
