version: '3.9'

services:
  apache:
    build:
      dockerfile: ./apache/Dockerfile
      context: .
    ports:
      - "80:80"
    volumes:
      - ./client/dist:/usr/local/apache2/htdocs
    depends_on:
      - demo_auth_website
      - frontend

  demo_auth_website:
    env_file:
      - api/.env/.env
    build:
      dockerfile: ./Dockerfile
      context: ./api
    command: ["/app/scripts/app.sh"]
    volumes:
      - ./api/alembic/versions:/app/alembic/versions
    depends_on:
      postgres_daw:
        condition: service_healthy
    ports:
     - "8080:8080"
      
  postgres_daw:
    image: postgres:16.1-alpine3.19
    restart: always
    env_file:
      - ./api/.env/.database.env
    volumes:
      - ./api/db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    command: npm run build
    volumes:
      - ./client:/app
      - /app/node_modules